language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - devel
matrix:
  include:
    - r: release
      os: linux
      after_success:
       - Rscript after.R
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_PAT
        on:
          branch: master
        local_dir: /docs
        target_branch: master-web
    - r: release
      os: osx
  exclude:
    - r: devel
      os: osx
notifications:
  email:
    - ben_barnard@outlook.com
  on_success: always
  on_failure: always